name: link-check

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed

jobs:
  link-check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [v16.7.0]

    steps:
      - name: Run linkcheck against post-deploy URL 🔗✅
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: https://codex.hl7.org/ -e
